WebAppLSV/Pages/Home/CargarArchivo.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebAppLSV.Modelo.DB;
using NPOI.HSSF.UserModel;
using NPOI.SS.UserModel;
using NPOI.XSSF.UserModel;

namespace WebAppLSV.Pages.Home
{
    public class CargarArchivoModel : PageModel
    {
        private readonly WebAppLSV.Modelo.DB.DBLSVContext _context;

        public CargarArchivoModel(WebAppLSV.Modelo.DB.DBLSVContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Controlarchivo Controlarchivo { get; set; }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Controlarchivo.Add(Controlarchivo);
            await _context.SaveChangesAsync();

            return RedirectToPage("/Home/ControlArchivo");
        }
    }
}

WebAppLSV/Pages/Home/ControlArchivo.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using WebAppLSV.Modelo.DB;
using WebAppLSV.Modelo;
using System.Data.Common;
using System.Data;
using System.Data.SqlClient;

namespace WebAppLSV.Pages.Home
{
    public class ControlArchivoModel : PageModel
    {
        private readonly WebAppLSV.Modelo.DB.DBLSVContext _context;

        public ControlArchivoModel(WebAppLSV.Modelo.DB.DBLSVContext context)
        {
            _context = context;
        }

        public IList<Controlarchivo> Controlarchivo { get;set; }
        public IList<Controlarchivo> ControlarchivoCargado { get; set; }

        [BindProperty]
        public ControlArchivoViewModel ControlarchivoVM { get; set; }

        public async Task OnGetAsync()
        {
            
 

            Controlarchivo = await _context.Controlarchivo
                                .Where(s=>s.Estado =="Cargado") 
                                .ToListAsync();

            
        }

       

        public async Task<IActionResult> OnPostProcesarArchivoAsync()
            
        {
            try
            {
                
                int v_error = 0;

                DbCommand cmd = _context.Database.GetDbConnection().CreateCommand();

                cmd.CommandText = "dbo.ProcesarArchivo";
                cmd.CommandType = CommandType.StoredProcedure;

                cmd.Parameters.Add(new SqlParameter("@IdArchivo", SqlDbType.Int) { Value = ControlarchivoVM.IdArchivo });
                cmd.Parameters.Add(new SqlParameter("@usuario", SqlDbType.VarChar) { Value = ControlarchivoVM.Usuario });

                cmd.Parameters.Add(new SqlParameter("@V_ERROR", SqlDbType.Int) { Direction = ParameterDirection.Output });

                if (cmd.Connection.State != ConnectionState.Open)
                {
                    cmd.Connection.Open();
                }

                await cmd.ExecuteNonQueryAsync();

                v_error = (int)cmd.Parameters["@V_ERROR"].Value;

            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
            }
            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostEliminarArchivoAsync()

        {
            try
            {
                Controlarchivo Archivo = await _context.Controlarchivo.FindAsync(ControlarchivoVM.IdArchivo);

                if (Archivo != null)
                {
                    _context.Controlarchivo.Remove(Archivo);
                    await _context.SaveChangesAsync();

                }

                

            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
            }

            return RedirectToPage();
        }
    }
}

WebAppLSV/Pages/Home/HistoricoCargarArchivo.cshtml.cs
#define SortFilterPage // SortFilterPage // SortFilter //SortOnly // first 

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using WebAppLSV.Modelo.DB;


namespace WebAppLSV.Pages.Home
{
    #region snippet1
    public class HistoricoCargarArchivoModel : PageModel
    {
        private readonly WebAppLSV.Modelo.DB.DBLSVContext _context;

        public HistoricoCargarArchivoModel(WebAppLSV.Modelo.DB.DBLSVContext context)
        {
            _context = context;
        }

        public string NameSort { get; set; }
        public string DateSort { get; set; }
        public string CurrentFilter { get; set; }
        public string CurrentSort { get; set; }
    #endregion
        //public PaginatedList<Controlarchivo> Controlarchivo { get; set; }

#if SortFilterPage

        #region snippet_SortFilterPageType

        public PaginatedList<Controlarchivo> Controlarchivo { get;set; }

        #endregion

#else

        public IList<Controlarchivo> Controlarchivo { get; set; }

#endif

#if first

        #region snippet_ScaffoldedIndex

        public async Task OnGetAsync()

        {

            Controlarchivo = await _context.Controlarchivo.ToListAsync();

        }

        #endregion

#endif

#if SortOnly

        #region snippet_SortOnly

        public async Task OnGetAsync(string sortOrder)

        {

        #region snippet_Ternary

            NameSort = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            DateSort = sortOrder == "Date" ? "date_desc" : "Date";

        #endregion



            IQueryable<Controlarchivo> ControlarchivoIQ = from s in _context.Controlarchivo
                                                            select s;



            switch (sortOrder)

            {

                case "name_desc":

                    ControlarchivoIQ = ControlarchivoIQ.OrderByDescending(s => s.Nombre);

                    break;

                case "Date":

                    ControlArchivoIQ = ControlarchivoIQ.OrderBy(s => s.Fecha_Proceso);

                    break;

                case "date_desc":

                    ControlArchivoIQ = ControlarchivoIQ.OrderByDescending(s => s.Fecha_Proceso);

                    break;

                default:

                    ControlArchivoIQ = ControlarchivoIQ.OrderBy(s => s.Nombre);

                    break;

            }



        #region snippet_SortOnlyRtn

            ControlArchivo = await ControlarchivoIQ.AsNoTracking().ToListAsync();

        #endregion

        }

        #endregion

#endif


#if SortFilter

        #region snippet_SortFilter

        public async Task OnGetAsync(string sortOrder, string searchString)

        {

            NameSort = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            DateSort = sortOrder == "Date" ? "date_desc" : "Date";

            CurrentFilter = searchString;



            IQueryable<Student> ControlArchivoIQ = from s in _context.ControlArchivo
                                                   select s;

            if (!String.IsNullOrEmpty(searchString))

            {

                ControlArchivoIQ = ControlArchivoIQ.Where(s => s.Nombre.Contains(searchString);
                                               
            }



            switch (sortOrder)

            {

                case "name_desc":

                    ControlArchivoIQ = ControlArchivoIQ.OrderByDescending(s => s.Nombre);

                    break;

                case "Date":

                    ControlArchivoIQ = ControlArchivoIQ.OrderBy(s => s.Fecha_Proceso);

                    break;

                case "date_desc":

                    ControlArchivoIQ = ControlArchivoIQ.OrderByDescending(s => s.Fecha_Proceso);

                    break;

                default:

                    ControlArchivoIQ = ControlArchivoIQ.OrderBy(s => s.Nombre);

                    break;

            }



            ControlArchivo = await ControlArchivoIQ.AsNoTracking().ToListAsync();

        }

        #endregion

#endif

#if SortFilterPage

        #region snippet_SortFilterPage

        #region snippet_SortFilterPage2

        public async Task OnGetAsync(string sortOrder,string currentFilter, string searchString, int? pageIndex)

        #endregion

        {

            DateTime fechaconsultaFIN = DateTime.Today;

            DateTime fechaconsultaINI = new DateTime(DateTime.Now.Year, DateTime.Now.Month, 1);

            CurrentSort = sortOrder;

            NameSort = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            DateSort = sortOrder == "Date" ? "date_desc" : "Date";

            #region snippet_SortFilterPage3

            if (searchString != null)

            {

                pageIndex = 1;

            }

            else

            {

                searchString = currentFilter;

            }

            #endregion



            CurrentFilter = searchString;



            IQueryable<Controlarchivo> ControlarchivoIQ = from s in _context.Controlarchivo
                                                          select s;



            ControlarchivoIQ = ControlarchivoIQ.Where(c => c.Estado == "Procesado")
                                    .Where(f => f.FechaCargar > fechaconsultaINI && f.FechaCargar < fechaconsultaFIN);      

            if (!String.IsNullOrEmpty(searchString))

            {

                ControlarchivoIQ = ControlarchivoIQ.Where(s => s.Nombre.Contains(searchString));

                                      
            }

            switch (sortOrder)

            {

                case "name_desc":

                    ControlarchivoIQ = ControlarchivoIQ.OrderByDescending(s => s.Nombre);

                    break;

                case "Date":

                    ControlarchivoIQ = ControlarchivoIQ.OrderBy(s => s.FechaProceso);

                    break;

                case "date_desc":

                    ControlarchivoIQ = ControlarchivoIQ.OrderByDescending(s => s.FechaProceso);

                    break;

                default:

                    ControlarchivoIQ = ControlarchivoIQ.OrderBy(s => s.Nombre);

                    break;

            }

            int pageSize = 5;

            #region snippet_SortFilterPage4

            Controlarchivo = await PaginatedList<Controlarchivo>.CreateAsync(ControlarchivoIQ.AsNoTracking(), pageIndex ?? 1, pageSize);

            #endregion

        }

        #endregion

#endif

        //public async Task OnGetAsync()
        //{
             

        //    DateTime fechaconsultaFIN = DateTime.Today;

        //    DateTime fechaconsultaINI = new DateTime(DateTime.Now.Year, DateTime.Now.Month, 1);

        //    Controlarchivo = await _context.Controlarchivo
        //                            .Where(c => c.Estado == "Procesado")
        //                            .Where(f => f.FechaCargar > fechaconsultaINI && f.FechaCargar < fechaconsultaFIN)
        //                            .ToListAsync();
        //}
    }
}

WebAppLSV/Pages/Home/Index.cshtml.cs
//-----------------------------------------------------------------------
// <copyright file="Index.cshtml.cs" company="None">
//     Copyright (c) Allow to distribute this code and utilize this code for personal or commercial purpose.
// </copyright>
// <author>Asma Khalid</author>
//-----------------------------------------------------------------------

namespace WebAppLSV.Pages.Home
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authentication;
    using Microsoft.AspNetCore.Authentication.Cookies;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.RazorPages;

    /// <summary>
    /// Index page model class.
    /// </summary>
    [Authorize]
    public class IndexModel : PageModel
    {
        #region On Get method.

        /// <summary>
        /// On Get method.
        /// </summary>
        public void OnGet()
        {
            try
            {
            }
            catch (Exception ex)
            {
                // Info
                Console.Write(ex);
            }
        }

        #endregion

 
    }
}

WebAppLSV/Pages/Home/CargarArchivo.cshtml
@page
@model WebAppLSV.Pages.Home.CargarArchivoModel

@{
    ViewBag.Title = "WebAPP Liseo Santa Verónica";
    ViewData["Title"] = "CargarArchivo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <h2>Archivos de Pagos</h2>
    <div class="row">
        <div class="col-md-4">
            <section>
                <form method="post" class="form-horizontal">

                    <div class="form-group">
                        <label asp-for="Controlarchivo.Nombre" class="control-label"></label>
                        <input type="file" asp-for="Controlarchivo.Nombre" class="form-control" />
                        <span asp-validation-for="Controlarchivo.Nombre" class="text-danger"></span>
                        <input type="hidden" asp-for="Controlarchivo.Usuario" class="form-control" value="@User.Identity.Name" />
                        <input type="hidden" asp-for="Controlarchivo.Estado" class="form-control" value="Cargado" />
                    </div>
                    <div class="form-group">
                        <label asp-for="Controlarchivo.Estado" class="control-label"></label>
                        <span asp-validation-for="Controlarchivo.Estado" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Controlarchivo.FechaCargar" class="control-label"></label>
                        <input type="datetime" asp-for="Controlarchivo.FechaCargar" class="form-control" value="@DateTime.Now" />
                        <span asp-validation-for="Controlarchivo.FechaCargar" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Controlarchivo.FechaProceso" class="control-label"></label>
                        <input type="datetime" asp-for="Controlarchivo.FechaProceso" class="form-control" value="@DateTime.Now" />
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Cargar" class="btn btn-primary" />
                    </div>

                </form>
            </section>
        </div>
    </div>
 
</div>
    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

WebAppLSV/Pages/Home/ControlArchivo.cshtml
@page
@model WebAppLSV.Pages.Home.ControlArchivoModel

@{
    ViewBag.Title = "WebAPP Liseo Santa Verónica";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h2>Archivos de Pagos Pendiente de Procesar</h2>
    <h2></h2>

    <form method="post" role="form" class="form-horizontal">
        <input type="hidden" asp-for="ControlarchivoVM.Usuario" class="form-control" value="@User.Identity.Name" />
        <div class="form-group">
            <a href="CargarArchivo" class="btn btn-primary"><span class="glyphicon glyphicon-upload"></span> Cargar Archivo..</a>
            <a href="HistoricoCargarArchivo" class="btn btn-primary"><span class="glyphicon glyphicon-check"></span> Historico</a>
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th>Nombre Archivo</th>
                    <th>Estado del Archivo</th>
                    <th>Fechar de Carga</th>
                    <th>Usuario</th>
                    <th>Operaciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Controlarchivo)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Nombre)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Estado)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.FechaCargar)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Usuario)
                        </td>
                        <td>
                            <input type="hidden" value="@item.Id" asp-for="ControlarchivoVM.IdArchivo" />
                            <button asp-page-handler="EliminarArchivo" class="btn btn-sm" title="Eliminar Archivo"> <span class="glyphicon glyphicon-remove"></span></button>
                            <button asp-page-handler="ProcesarArchivo" class="btn btn-sm" title="Procesar Archivo"> <span class="glyphicon glyphicon-refresh"></span></button>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </form>
</div>

WebAppLSV/Pages/Home/HistoricoCargarArchivo.cshtml
@page
@model WebAppLSV.Pages.Home.HistoricoCargarArchivoModel

@{
    ViewBag.Title = "WebAPP Liseo Santa Verónica";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <h2>Archivos de Pagos Cargados en el mes de @DateTime.Now.ToString("MMMM")</h2>

    <form asp-page="./HistoricoCargarArchivo" method="get">
        <div class="form-actions no-color">
            <p>
                Buscar por nombre de Archivo: <input type="text" name="SearchString" value="@Model.CurrentFilter" />
                <input type="submit" value="Search" class="btn btn-default" /> |
                <a asp-page="./HistoricoCargarArchivo">Lista Completa</a>
            </p>
        </div>
    </form>
    <table class="table">
        <thead>
            <tr>
                <th>
                    <a asp-page="./HistoricoCargarArchivo" asp-route-sortOrder="@Model.NameSort"
                       asp-route-currentFilter="@Model.CurrentFilter">
                        @Html.DisplayNameFor(model => model.Controlarchivo[0].Nombre)
                    </a>
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Controlarchivo[0].Estado)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Controlarchivo[0].FechaCargar)
                </th>
                <th>
                    <a asp-page="./HistoricoCargarArchivo" asp-route-sortOrder="@Model.DateSort"
                       asp-route-currentFilter="@Model.CurrentFilter">
                        @Html.DisplayNameFor(model => model.Controlarchivo[0].FechaProceso)
                    </a>

                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Controlarchivo[0].Usuario)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Controlarchivo)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nombre)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Estado)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FechaCargar)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FechaProceso)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Usuario)
                    </td>
                </tr>
            }
        </tbody>
    </table> 
    @{

        var prevDisabled = !Model.Controlarchivo.HasPreviousPage ? "disabled" : "";

        var nextDisabled = !Model.Controlarchivo.HasNextPage ? "disabled" : "";

    }

    <a asp-page="./HistoricoCargarArchivo"
       asp-route-sortOrder="@Model.CurrentSort"
       asp-route-pageIndex="@(Model.Controlarchivo.PageIndex - 1)"
       asp-route-currentFilter="@Model.CurrentFilter"
       class="btn btn-default @prevDisabled">
        Anterior

    </a>
    <a asp-page="./HistoricoCargarArchivo"
       asp-route-sortOrder="@Model.CurrentSort"
       asp-route-pageIndex="@(Model.Controlarchivo.PageIndex + 1)"
       asp-route-currentFilter="@Model.CurrentFilter"
       class="btn btn-default @nextDisabled">
        Siguiente

    </a>
</div>

WebAppLSV/Pages/Home/Index.cshtml
@page



@model WebAppLSV.Pages.Home.IndexModel

@{
    ViewBag.Title = "WebAPP Liseo Santa Verónica";
}


<div class="jumbotron">
    <h1>Bienvenido</h1>
    <p class="lead">Usuario: "@User.Identity.Name".</p>

</div>